### PR TITLE
CI on GitHub Actions

### PR DESCRIPTION
**Pull request by taichi-ishitani**
Hi @saveriomiroddi ,

This PR is to enable CI on GitHub Actions.
I will also disable CI on travis-ci if you need.

### CODE REVIEW

**Comment by taichi-ishitani** [comment]
I think you need to enable GitHub Actions on your repository.
https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#managing-github-actions-permissions-for-your-repository

**Review by 64kramsystem — COMMENTED** [review]
The `RUBY_VERSION` check can be removed from this PR, as it will be added to master by #18.

**Comment by 64kramsystem** [comment]
>  I will also disable CI on travis-ci if you need.

Yes, thanks! I think it's appropriate to add this change, after #18 has been merged, since Travis is a thing of the past now! :smile:

**Comment by 64kramsystem** [comment]
@taichi-ishitani Hello! Two notes:

1. Can you rebase the branch on master? There was a conflict; I've resolved it, but rebasing will get rid of a wasteful commit
2. As far as you know, should the Github action for CI show in the list of the checks for this PR? I currently only see the CodeClimate one. I'm not familiar with Github actions :grimacing: 

Thanks for your work! :smile:

**Comment by taichi-ishitani** [comment]
Hi @saveriomiroddi ,

1. I've rebased the branch on master.
2. It's seemed that Actions has been enabled. 
https://github.com/saveriomiroddi/spreadbase/actions/runs/624402431

**Comment by taichi-ishitani** [comment]
FYI:
You can get the status badge by clicking the `create status badge` button on the upper right side.

image

**Comment by taichi-ishitani** [comment]
CI on Github actions works now so we can disable CI on travis-ci.
Can I remove the `.travis.yml` file?

**Comment by 64kramsystem** [comment]
@taichi-ishitani thanks for everything :smile: 

Yes, I've enabled the actions, following your notification :smile: 

Feel free to remove the Travis configfile if you want; if you also want to add the badge to the README. Either way, I'll take care of what's left after the merge :smile:

After you're going the next change/s, I'm going to merge :smile:

**Comment by taichi-ishitani** [comment]
I've done:

* Disable CI on travis-ci
* Replace the status badge on README

**Comment by 64kramsystem** [comment]
Excellent! Thanks for the contributions :smile:

**Comment by taichi-ishitani** [comment]
Thank you for merging my PR.

BTW, there is following sentence on README.

```
The gem has been tested on Ruby 1.9.3-p125, on Linux and Mac OS X.
```

We're testing on Ruby 2.3 - 3.0 so I think we should update this sentence.

**Comment by 64kramsystem** [comment]
> Thank you for merging my PR.
> 
> BTW, there is following sentence on README.
> 
> ```
> The gem has been tested on Ruby 1.9.3-p125, on Linux and Mac OS X.
> ```
> 
> We're testing on Ruby 2.3 - 3.0 so I think we should update this sentence.

Thanks! I've created a tracking issue for that, for whoever comes :smile: 

I've just released v0.2.1, with your recent contributions. I'm creating an issue also for the loose rubyzip dependency, which I'm taking care of now:

```
WARNING:  open-ended dependency on rubyzip (>= 1.3.0) is not recommended
  if rubyzip is semantically versioned, use:
    add_runtime_dependency 'rubyzip', '~> 1.3', '>= 1.3.0'
```

**Pull request merged**
